In [2]:
import numpy as np

array=np.arange(15).reshape(3, 5)
ar1=array
ar2=array
print(ar1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
print(ar2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
res=ar1+ar2
print(res)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]


In [8]:
a=np.zeros((3,4), dtype=int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [12]:
b=np.ones((2,3,4))
print(b)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [13]:
c=np.arange(2, 10, 2)
print(c)

[2 4 6 8]


In [15]:
d=np.linspace(0, 10, 5)
print(d)

[ 0.   2.5  5.   7.5 10. ]


In [28]:
from numpy import pi
e=np.linspace(0, 2*pi, 10)
print(e)
print(e.size)

[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]
10


In [27]:
f=np.tan(pi/4)
print(f)

0.9999999999999999


In [31]:
e=e.reshape(5,2)
print(e)

[[0.         0.6981317 ]
 [1.3962634  2.0943951 ]
 [2.7925268  3.4906585 ]
 [4.1887902  4.88692191]
 [5.58505361 6.28318531]]


In [32]:
g=np.zeros_like(a)
print(g)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [33]:
h=np.ones_like(b)
print(h)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [40]:
i=np.random.RandomState(42)
print(i.rand(2,3))

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]


In [41]:
i=i.randn(2,3)
print(i)

[[ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]]
